@echo off
chcp 65001 >nul
setlocal
REM ============================================================
REM  注册开机自启（当前用户，不需要管理员，不碰注册表）
REM  做法：在「启动」文件夹里放一个静默启动器。
REM  想取消：双击 uninstall-autostart.bat，或直接删掉那个文件。
REM ============================================================

set "ROOT=%~dp0"
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "TARGET=%STARTUP%\SolveBase.vbs"

if not exist "%ROOT%start.bat" (
  echo [错误] 同目录下找不到 start.bat，脚本位置不对。
  pause
  exit /b 1
)

if not exist "%STARTUP%" mkdir "%STARTUP%"

> "%TARGET%" echo ' SolveBase auto-start. Generated by install-autostart.bat
>>"%TARGET%" echo ' Delete this file to disable auto-start.
>>"%TARGET%" echo Set sh = CreateObject("WScript.Shell")
>>"%TARGET%" echo sh.Run """%ROOT%start.bat"" silent", 0, False

if not exist "%TARGET%" (
  echo [失败] 写入启动文件夹被拒绝，可能是安全软件拦截。
  pause
  exit /b 1
)

echo 开机自启已注册。
echo   启动器： %TARGET%
echo   指向：   %ROOT%start.bat  ^(silent 模式，无黑窗口，不自动开浏览器^)
echo.
echo 下次开机后直接在浏览器打开 http://127.0.0.1:8787 即可。
echo 建议把这个地址设成书签或浏览器主页。
echo.
echo 取消自启：双击 uninstall-autostart.bat
pause
exit /b 0
